version: '3'
services:
        pulsar:
                build: ./pulsar
                ports:
                        - 6650:6650
                        - 8000:8000
                        - 8080:8080
                volumes:
                        - ./data:/pulsar/data
                        - ./connectors-dist:/connectors-dist
                command: ["bin/pulsar", "standalone"]
        web:
                build: ./web
                ports:
                        - 5000:5000
