version: '3'
services:
        pulsar:
                image: apachepulsar/pulsar:2.4.0
                ports:
                        - 6650:6650
                        - 8000:8000
                        - 8080:8080
                volumes:
                        - ./data:/pulsar/data
                command: ["bin/pulsar", "standalone"]
        web:
                build: ./web
                ports:
                        - 5000:5000
